
services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle     
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
    depends_on:
      - db
      - redis
  
  


  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webops_blog_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db


volumes:
  pgdata:
  bundle:  # ← add this
